//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annee
    {
        public Annee()
        {
            this.UE = new HashSet<UE>();
        }
    
        public int id { get; set; }
        public string intitule { get; set; }
        public int diplomeID { get; set; }
        public int ordre { get; set; }
    
        public virtual Diplome Diplome { get; set; }
        public virtual ICollection<UE> UE { get; set; }
    }
}
