//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.EquivalentTD = new HashSet<EquivalentTD>();
            this.Personnel = new HashSet<Personnel>();
        }
    
        public int id { get; set; }
        public string intitule { get; set; }
        public int nbEQTD { get; set; }
    
        public virtual ICollection<EquivalentTD> EquivalentTD { get; set; }
        public virtual ICollection<Personnel> Personnel { get; set; }
    }
}
