//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composante
    {
        public Composante()
        {
            this.Departement = new HashSet<Departement>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
    
        public virtual ICollection<Departement> Departement { get; set; }
    }
}
