//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.EnseignantCours = new HashSet<EnseignantCours>();
        }
    
        public int id { get; set; }
        public string intitule { get; set; }
        public short nbGroupes { get; set; }
        public int nbHeures { get; set; }
        public int typeCoursID { get; set; }
        public int idEC { get; set; }
    
        public virtual EC EC { get; set; }
        public virtual TypeCours TypeCours { get; set; }
        public virtual ICollection<EnseignantCours> EnseignantCours { get; set; }
    }
}
