//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public Departement()
        {
            this.Diplome = new HashSet<Diplome>();
            this.Personnel = new HashSet<Personnel>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int composanteID { get; set; }
    
        public virtual Composante Composante { get; set; }
        public virtual ICollection<Diplome> Diplome { get; set; }
        public virtual ICollection<Personnel> Personnel { get; set; }
    }
}
