//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplome
    {
        public Diplome()
        {
            this.Annee = new HashSet<Annee>();
        }
    
        public int id { get; set; }
        public string intitule { get; set; }
        public int departementID { get; set; }
        public int nbAnnees { get; set; }
    
        public virtual ICollection<Annee> Annee { get; set; }
        public virtual Departement Departement { get; set; }
    }
}
