//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class Personnel
    {
        public Personnel()
        {
            this.EnseignantCours = new HashSet<EnseignantCours>();
            this.Departement = new HashSet<Departement>();
        }

        public Personnel(string nom, string prenom)
        {
            this.nom = textInfo.ToTitleCase(nom.ToLower());
            this.prenom = textInfo.ToTitleCase(prenom.ToLower());
        }

        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public int categorieID { get; set; }

        public virtual Categorie Categorie { get; set; }
        public virtual ICollection<EnseignantCours> EnseignantCours { get; set; }
        public virtual ICollection<Departement> Departement { get; set; }

        private TextInfo textInfo = new CultureInfo("fr-FR", false).TextInfo;

        public string identite
        {
            get
            {
                if (id > 0)
                {
                    return nom.ToUpperInvariant() + " " + textInfo.ToTitleCase(prenom.ToLower());
                }
                else
                {
                    return "Aucun";
                }
            }
        }
    }
}
