//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCours
    {
        public TypeCours()
        {
            this.Cours = new HashSet<Cours>();
            this.EquivalentTD = new HashSet<EquivalentTD>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
    
        public virtual ICollection<Cours> Cours { get; set; }
        public virtual ICollection<EquivalentTD> EquivalentTD { get; set; }
    }
}
