//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Collections.Generic;
    
    public partial class UE
    {
        public UE()
        {
            this.EC = new HashSet<EC>();
            this.Annee = new HashSet<Annee>();
        }
    
        public int id { get; set; }
        public string abbreviation { get; set; }
        public string nomComplet { get; set; }
        public short semestre { get; set; }
    
        public virtual ICollection<EC> EC { get; set; }
        public virtual ICollection<Annee> Annee { get; set; }
    }
}
