//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annee> Annee { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Composante> Composante { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<Diplome> Diplome { get; set; }
        public virtual DbSet<EC> EC { get; set; }
        public virtual DbSet<EnseignantCours> EnseignantCours { get; set; }
        public virtual DbSet<EquivalentTD> EquivalentTD { get; set; }
        public virtual DbSet<Personnel> Personnel { get; set; }
        public virtual DbSet<TypeCours> TypeCours { get; set; }
        public virtual DbSet<UE> UE { get; set; }
    }
}
